# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
  secret: '%env(APP_SECRET)%'
  #csrf_protection: true
  #http_method_override: true

  # Enables session support. Note that the session will ONLY be started if you read or write from it.
  # Remove or comment this section to explicitly disable session support.
  session:
    handler_id: null
    cookie_secure: auto
    cookie_samesite: lax

  #esi: true
  #fragments: true
  php_errors:
    log: true

  http_client:
    scoped_clients:
      github_client:
        base_uri: 'https://api.github.com'
        headers:
          Accept: 'application/vnd.github.v4+json'
          Authorization: 'bearer %env(GITHUB_ACCESS_TOKEN)%'
