#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: default/index.html.twig
