#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_home_v2:
  path: /v2
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: default/alt.html.twig
