#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_me:
  path: /me
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: default/me.html.twig

app_about:
  path: /about
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: default/about.html.twig
